name: ocean_figures
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - folium
  - geopandas
  - iris
  - jupyter
  - nb_conda_kernels
  - nbdime
  - oceans
  - palettable
  - pandas
  - shapely
